package hook

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/urfave/cli/v3"
)

const bashEvalCommand = `eval "$(peon hook bash)"`

func bashCommand() *cli.Command {
	return &cli.Command{
		Name:  "bash",
		Usage: "Returns Bash initialization code",
		Action: func(ctx context.Context, cmd *cli.Command) error {
			exePath, err := os.Executable()
			if err != nil {
				return err
			}

			path, err := filepath.EvalSymlinks(exePath)
			if err != nil {
				return err
			}

			fmt.Printf(`# Generated by https://github.com/atomicptr/peon, please do not edit
__peon_cd() {
	cd "$1" || return
}

peon() {
	orders=$(mktemp)

	PEON_ORDERS="$orders" command %s "$@"

	if [ -s "$orders" ]; then
		eval "$(<"$orders")"
		rm -f "$orders"
	fi
}`, path)

			return nil
		},
	}
}
