package hook

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/urfave/cli/v3"
)

const zshName = "zsh"
const zshEvalCommand = `eval "$(peon hook zsh)"`

func zshCommand() *cli.Command {
	return &cli.Command{
		Name:  zshName,
		Usage: "Returns zsh initialization code",
		Action: func(ctx context.Context, cmd *cli.Command) error {
			exePath, err := os.Executable()
			if err != nil {
				return err
			}

			path, err := filepath.EvalSymlinks(exePath)
			if err != nil {
				return err
			}

			fmt.Printf(`# Generated by https://github.com/atomicptr/peon, please do not edit
__peon_cd() {
	cd "$1"
}

peon() {
	local orders=$(mktemp)

	PEON_ORDERS="$orders" command %s "$@"

	if [[ -s "$orders" ]]; then
		eval "$(cat "$orders")"
		rm -f "$orders"
	fi
}`, path)

			return nil
		},
	}
}
