package shell

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/urfave/cli/v3"
)

func fishCommand() *cli.Command {
	return &cli.Command{
		Name:  "fish",
		Usage: "Returns Fish initialization code",
		Action: func(ctx context.Context, cmd *cli.Command) error {
			exePath, err := os.Executable()
			if err != nil {
				return err
			}

			path, err := filepath.EvalSymlinks(exePath)
			if err != nil {
				return err
			}

			fmt.Printf(`# Generated by https://github.com/atomicptr/peon, please do not edit
function __peon_cd
	cd $argv[1]
end

function peon
    set -l orders (mktemp)

    PEON_ORDERS="$orders" command %s $argv

    if test -s "$orders"
        eval (cat "$orders")
		rm -f "$orders"
    end
end`, path)

			return nil
		},
	}
}
