on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v7
        with:
          go-version: '^1.26'
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.14
      - uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
